### ISSUE TITLE
sprint: Sprint-Templates kick-off

### ISSUE THREAD

**Issue by tiborsimko** [cernopendata/cernopendata-pages#2]
# Sprint-Templates Kick-Off 

## Date 

2017-07-05
2017-07-19 : Cases for each URL updated by @daslerr
2017-07-19 : Updated cases for about pages @daslerr
2017-08-22: Updated cases and links as new issues are created @tiborsimko

## People

@annatrz @daslerr @hjhsalo @ioannistsanaktsidis @pamfilos @sefeg @tiborsimko

## Goals

- Move templates from old Invenio-2-based site to new Invenio-3-based site.
- Adopt new IA/UX/UI discussed [elsewhere](https://github.com/cernopendata/opendata.cern.ch/issues/1228).
- Make sure that all old URLs (see the map below) reply.

### Case 1: Records

Currently, having only records:

- **record** representing datasets, software, vm, documentation etc. Following
MARCXML in Invenio2 and a new custom JSON schema in Invenio3. URL is
``/record/123``.

We shall introduce several new record types:

- **glossary** representing glossary terms, with a simple JSON schema
  ``glossary.{id,...}`` matching [glossary.json](https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/static/json/glossary.json).
  URL is ``/glossary/<id=term>``.

- **article** representing any "guides" and "posts" etc, with simple JSON
  schema like `article.{id,title,type,body,files,collection}`. URL is
  ``/articles/<id=how-to-do-foo>``. ``type`` could be ``markdown`` or ``rest``.

Later, we could even think of splitting **record** into **dataset**,
**software** etc depending on the data model evolution.

Note that for each record type, we need to introduce nice HTML brief and detailed template, nice serialisation into say DublinCore etc formats we want to support, etc.

### Case 2: Simple pages

Most of the current pages will be transformed to records.

Some of the simplest pages, if we don't want to make them searchable, will
remain as Jinja templates.

Example: ``/terms-of-use``.

### Case 3: Collections

Some of the old pages may be transformed to collections.

Example: `VM`.

### Case 4: Aliases

Some of the old pages may be aliases to new faceted search page.
Page which is a search alias will use the usual search view, not it's own template.

Example: ``/resources/<string:exp>``.

## Tasks

The current URL map in Invenio2 looks like:

- [x] /
  - Changes to About-dropdown menu #7 
  - Education and Research sections don't scale correctly on smaller screens.
  - More homepage tasks / issues will be added.
- [x] //static/<path:filename>
  - *not necessary to port over*
- [x] /<string:exp>/getstarted
  - case 4 - Alias to Faceted Search
- [x] /VM
  - case 3 - Collection. *Collection of Articles about individual VM releases*
- [x] /VM/<exp>/validation/report
  - case 1 - Record (Article)
- [x] /VM/<string:exp>
  - case 3 - Collection. *Collection of Articles about individual VM releases from the specified experiment*
- [x] /VM/<string:exp>/<string:year>
  - case 1 - Record (Article)
- [x] /about
  - case 2 - Page
  - #6 
- [x] /about/ALICE
  - case 2 - Page
  - #8 
  - Alias: /about/alice
- [x] /about/ATLAS
  - case 2 - Page
  - #11 
  - Alias: /about/atlas
- [x] /about/CMS
  - case 2 - Page
  - #10 
  - Alias: /about/cms
- [x] /about/CMS-Physics-Objects
  - case 2 - Page
  - #13 
- [x] /about/CMS-Physics-Objects/<string:year>
  - case 2 - Page
  - #13 
- [x] /about/CMS-Pileup-Simulation
  - case 2 - Page
  - *might be implemented as a generic record (case 1) in the future; no detailed granularity in schema structure, content simply under content-key possibly as Markdown.*
  - #14
- [x] /about/CMS-Simulated-Dataset-Names
  - case 2 - Page
  - *might be implemented as a generic record (case 1) in the future; no detailed granularity in schema structure, content simply under content-key possibly as Markdown.*
  - #15
- [x] /about/LHCb
  - case 2 - Page
  - #12 
  - Alias: /about/lhcb
- [x] /about/OPERA
  - Currently not available from CERN Open Data Portal.
  - Invenio2-based implementation is however available:
    https://github.com/cernopendata/opendata.cern.ch/blob/master/invenio_opendata/base/templates/about_opera.html
  - Alias: /about/opera
- [x] /collection
  - case 3 - Collection
  - Alias: /collections
  - Alias: /experiments
- [x] /collection/<name>
  - case 3 - Collection
- [x] /education
  - case 4 - Alias to Faceted Search
  - *"Education" may or may not become a tag for a Record, depending on whether we determine more specific tags*
  - #16 
- [x] /education/<string:exp>
  - case 3 - Collection
  - *_Note:_ There needs to be a view for each experiment, which will replace the current /education/<string:exp> and /research/<string:exp>. So eventually there will be a CMS Collection (for example), but not an /education/CMS Collection.*
- [x] /getstarted/<string:exp>
  - case 4 - Alias to Faceted Search
  - *Currently alias of /getting-started*
- [x] /getting-started
  - case 4 - Alias to Faceted Search
  - *"Getting started" (or similar) will become a tag in an Article record.*
  - *Currently /getstarted is an alias of this*
- [x] /getting-started/<string:exp>
  - case 4 - Alias to Faceted Search
- [x] /getting-started/<string:exp>/<string:year>
  - case 1 - Record (Article)
  - *Each getting started page will become an Article and will be tagged with experiment and year.*
- [x] /glossary
  - https://github.com/cernopendata/cernopendata/issues/7
  - https://github.com/cernopendata/cernopendata-fixtures/issues/3
  - https://github.com/cernopendata/cernopendata-pages/issues/4
- [x] /news
  - case 3 - Collection
  - *Collection of Articles.*
- [x] /privacy-policy
  - case 2 - Page
   - #21 
- [x] /record/<int:recid>
  - case 1 - Record
- [x] /record/<int:recid>/
  - case 1 - Record
- [x] /record/<int:recid>/citations
  - case 1 - Record
- [x] /record/<int:recid>/export
  - case 1 - Record
- [x] /record/<int:recid>/export/<of>
  - case 1 - Record
- [x] /record/<int:recid>/files
  - case 1 - Record
- [x] /record/<int:recid>/keywords
  - case 1 - Record
- [x] /record/<int:recid>/load/authors/
  - case 1 - Record
  - https://github.com/cernopendata/opendata.cern.ch/issues/1322
- [x] /record/<int:recid>/load/authors/<int:start>/to/<int:end>
  - case 1 - Record
  - https://github.com/cernopendata/opendata.cern.ch/issues/1322
- [x] /record/<int:recid>/load/files/
  - case 1 - Record 
  - https://github.com/cernopendata/opendata.cern.ch/issues/1322
- [x] /record/<int:recid>/load/files/<int:start>/to/<int:end>
  - case 1 - Record
  - https://github.com/cernopendata/opendata.cern.ch/issues/1322
- [x] /record/<int:recid>/metadata
  - case 1 - Record
- [x] /record/<int:recid>/references
  - case 1 - Record
- [x] /record/<int:recid>/usage
  - case 1 - Record
- [x] /research
  - case 4 - Alias to Faceted Search
  - *"Research" may or may not become a tag for a Record, depending on whether we determine more specific tags*
- [x] /research/<string:exp>
  - case 3 - Collection
  - *_Note:_ There needs to be a view for each experiment, which will replace the current /education/<string:exp> and /research/<string:exp>. So eventually there will be a CMS Collection (for example), but not a /research/CMS Collection.*
- [x] /resources
  - case 4 - Alias to Faceted Search
- [x] /resources/<string:exp>
  - case 4 - Alias to Faceted Search
- [x] /terms-of-use 
  - case 2 - Page
  - #3
- [x] /visualise/events/<string:exp>
  - case 2 - Page
  - *Simple page with previewer plugged in*
  - https://github.com/cernopendata/opendata.cern.ch/issues/1317
  - https://github.com/cernopendata/opendata.cern.ch/issues/1318
  - https://github.com/cernopendata/opendata.cern.ch/issues/1319
  - https://github.com/cernopendata/opendata.cern.ch/issues/1320
- [x] /visualise/histograms/<string:exp>
  - case 2 - Page
  - *Simple page with histogramming plugged in*
  - https://github.com/cernopendata/opendata.cern.ch/issues/1321
- [x] /youraccount/
  - *no need to port over, just make sure accounts are not available*
- [x] /youraccount/access
- [x] /youraccount/display
- [x] /youraccount/edit/<name>
- [x] /youraccount/login
- [x] /youraccount/logout
- [x] /youraccount/lost
- [x] /youraccount/register
- [x] /youraccount/view

**TODO** For each URL above, we have to 
- decide whether it'll be transformed to a Record, Page, Collection, or Alias
- create a separate GitHub issue
- cross it out from the table above

## Kanban

Kanban board: https://waffle.io/cernopendata/opendata.cern.ch?milestone=Sprint-Templates

**Comment by daslerr** [comment]
My understanding from what we discussed in the meeting was that the about pages would be converted to article record types. Let's discuss in the weekly, and I can update the issue if need be.

**Comment by daslerr** [comment]
I've updated the original comment with the cases. Objections welcome.

**Comment by daslerr** [comment]
I updated the case list to reflect our chat conversation - The about pages do not need to be records.

**Comment by ioannistsanaktsidis** [comment]
@daslerr @tiborsimko  concerning /youraccount/ pages I guess we can cross them over as login is not supported and there are not any URLs associated with an account. Is it ok if I remove them or am I missing something ?

**Comment by tiborsimko** [comment]
@ioannistsanaktsidis Yes, I just checked them out.  The task was simply to make sure that the accounts are not enabled :)

**Comment by tiborsimko** [comment]
Created a plethora of dedicated issues at https://github.com/cernopendata/opendata.cern.ch/milestone/22

Closing.
